export const A8 = document.getElementById('A8')
export const B8 = document.getElementById('B8')
export const C8 = document.getElementById('C8')
export const D8 = document.getElementById('D8')
export const E8 = document.getElementById('E8')
export const F8 = document.getElementById('F8')
export const G8 = document.getElementById('G8')
export const H8 = document.getElementById('H8')

export const A7 = document.getElementById('A7')
export const B7 = document.getElementById('B7')
export const C7 = document.getElementById('C7')
export const D7 = document.getElementById('D7')
export const E7 = document.getElementById('E7')
export const F7 = document.getElementById('F7')
export const G7 = document.getElementById('G7')
export const H7 = document.getElementById('H7')

export const A6 = document.getElementById('A6')
export const B6 = document.getElementById('B6')
export const C6 = document.getElementById('C6')
export const D6 = document.getElementById('D6')
export const E6 = document.getElementById('E6')
export const F6 = document.getElementById('F6')
export const G6 = document.getElementById('G6')
export const H6 = document.getElementById('H6')

export const A5 = document.getElementById('A5')
export const B5 = document.getElementById('B5')
export const C5 = document.getElementById('C5')
export const D5 = document.getElementById('D5')
export const E5 = document.getElementById('E5')
export const F5 = document.getElementById('F5')
export const G5 = document.getElementById('G5')
export const H5 = document.getElementById('H5')

export const A4 = document.getElementById('A4')
export const B4 = document.getElementById('B4')
export const C4 = document.getElementById('C4')
export const D4 = document.getElementById('D4')
export const E4 = document.getElementById('E4')
export const F4 = document.getElementById('F4')
export const G4 = document.getElementById('G4')
export const H4 = document.getElementById('H4')

export const A3 = document.getElementById('A3')
export const B3 = document.getElementById('B3')
export const C3 = document.getElementById('C3')
export const D3 = document.getElementById('D3')
export const E3 = document.getElementById('E3')
export const F3 = document.getElementById('F3')
export const G3 = document.getElementById('G3')
export const H3 = document.getElementById('H3')

export const A2 = document.getElementById('A2')
export const B2 = document.getElementById('B2')
export const C2 = document.getElementById('C2')
export const D2 = document.getElementById('D2')
export const E2 = document.getElementById('E2')
export const F2 = document.getElementById('F2')
export const G2 = document.getElementById('G2')
export const H2 = document.getElementById('H2')

export const A1 = document.getElementById('A1')
export const B1 = document.getElementById('B1')
export const C1 = document.getElementById('C1')
export const D1 = document.getElementById('D1')
export const E1 = document.getElementById('E1')
export const F1 = document.getElementById('F1')
export const G1 = document.getElementById('G1')
export const H1 = document.getElementById('H1')