const A1 = document.getElementById('A1')
const B1 = document.getElementById('B1')
const C1 = document.getElementById('C1')
const D1 = document.getElementById('D1')
const E1 = document.getElementById('E1')
const F1 = document.getElementById('F1')
const G1 = document.getElementById('G1')
const H1 = document.getElementById('H1')